name: mongo
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
   alfred: ^1.1.1
   mongo_dart: ^0.9.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
